[
  {
    "Carimbo de data/hora": "07/07/2025 18:23:19",
    "Nome completo": "Ana Clara Negri Santos",
    "Razão Social do prestador de serviços": "58.239.035 ANA CLARA NEGRI SANTOS",
    "Número do CNPJ": "58239035000168",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.05,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "077 - inter",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 406104697,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 58239035000168,
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Física",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": 58239035000168,
    "Número da nota fiscal (INFLUENCER)": "35414062258239035000168000000000001225072299368301",
    "Valor a pagar da nota fiscal (INFLUENCER)": 2084.9,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=15U1L7sBvhY35E_5C9jM-gKRb2v2tg2w5",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "anacnegri@icloud.com",
    "Status (influ)": "Não validado",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Correto",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "58239035000168",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 9600,
    "ValorMensal_Planilha": 1600,
    "ValorMensal_Influ": 1600,
    "ValorMensal_Assessoria": 0,
    "QtD_NFs": 6
  },
  {
    "Carimbo de data/hora": "02/07/2025 15:03:02",
    "Nome completo": "DANIEL ARAGAO LOUZADA LTDA",
    "Razão Social do prestador de serviços": "DANIEL ARAGAO LOUZADA LTDA",
    "Número do CNPJ": "53081863000105",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.05,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "Inter",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "32658646-6",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "53.081.863/0001-05",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "53.081.863/0001-05",
    "Número da nota fiscal (INFLUENCER)": 19,
    "Valor a pagar da nota fiscal (INFLUENCER)": 2000,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1mZgFwnLRYpUYN6NOzwJENEQv8shCEcEX",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "Não foi possível ler a NF",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Não foi possível ler a NF",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "53081863000105",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 7500,
    "ValorMensal_Planilha": 2500,
    "ValorMensal_Influ": 2000,
    "ValorMensal_Assessoria": 500,
    "QtD_NFs": 3
  },
  {
    "Carimbo de data/hora": "01/07/2025 18:35:22",
    "Nome completo": "WUPPER DIGITAL AGENCIA LTDA\n",
    "Razão Social do prestador de serviços": "WUPPER DIGITAL AGENCIA LTDA\n",
    "Número do CNPJ": "39440918000197",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": "Não sou comissionada (o)",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "CAIXA ECONOMICA FEDERAL\n",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1017,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "000578314402-5\n",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "39.440.918/0001-97",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "39.440.918/0001-97",
    "Número da nota fiscal (INFLUENCER)": "2025/655",
    "Valor a pagar da nota fiscal (INFLUENCER)": 13500,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=14a5NOgLEx2afUe-KPfl6sQxvU1IDsJKq",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "Não foi possível ler a NF",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Não foi possível ler a NF",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "39440918000197",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 114000,
    "ValorMensal_Planilha": 9500,
    "ValorMensal_Influ": 9500,
    "ValorMensal_Assessoria": 0,
    "QtD_NFs": 12
  },
  {
    "Carimbo de data/hora": "04/07/2025 10:26:32",
    "Nome completo": "BEATRIZ L BOEKE LTDA",
    "Razão Social do prestador de serviços": "BEATRIZ L BOEKE LTDA",
    "Número do CNPJ": "54370484000190",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.05,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "Nubank",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "89181485-2",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "54.370.484/0001-90",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "54.370.484/0001-90",
    "Número da nota fiscal (INFLUENCER)": 48,
    "Valor a pagar da nota fiscal (INFLUENCER)": 6400,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1-T9spXH4dv56JTZyNjrR8I-ZvdTGEqCE",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "danila@4pillarsagencia.com",
    "Status (influ)": "Não foi possível ler a NF",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Não foi possível ler a NF",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "54370484000190",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 24000,
    "ValorMensal_Planilha": 8000,
    "ValorMensal_Influ": 6400,
    "ValorMensal_Assessoria": 1600,
    "QtD_NFs": 3
  },
  {
    "Carimbo de data/hora": "02/07/2025 15:11:46",
    "Nome completo": "BEATRIZ FIDELIS MARKETING DIGITAL LTDA",
    "Razão Social do prestador de serviços": "BEATRIZ FIDELIS MARKETING DIGITAL LTDA",
    "Número do CNPJ": "52213611000111",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.05,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "Inter",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "35843051-8",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "52.213.611/0001-11",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "52.213.611/0001-11",
    "Número da nota fiscal (INFLUENCER)": 26,
    "Valor a pagar da nota fiscal (INFLUENCER)": 2100,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1ZEVCrruno5Sx70MfA4aNxmjsKI_U5Dzi",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "Não foi possível ler a NF",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Não foi possível ler a NF",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "52213611000111",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 9000,
    "ValorMensal_Planilha": 3000,
    "ValorMensal_Influ": 2100,
    "ValorMensal_Assessoria": 900,
    "QtD_NFs": 3
  },
  {
    "Carimbo de data/hora": "02/07/2025 15:42:28",
    "Nome completo": "Camila Pereira Barbosa",
    "Razão Social do prestador de serviços": "CAMILA E CIA MIDIAS DIGTAIS LTDA",
    "Número do CNPJ": "50645390000125",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.08,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "Inter",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "29126801-3",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "50.645.390/0001-25",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "50.645.390/0001-25",
    "Número da nota fiscal (INFLUENCER)": 134,
    "Valor a pagar da nota fiscal (INFLUENCER)": 3656.18,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1V83yActiv4obaEQ06M2W06xdx2WxNZu-",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "Não foi possível ler a NF",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Não foi possível ler a NF",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "50645390000125",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 24000,
    "ValorMensal_Planilha": 2000,
    "ValorMensal_Influ": 2000,
    "ValorMensal_Assessoria": 0,
    "QtD_NFs": 12
  },
  {
    "Carimbo de data/hora": "02/07/2025 14:47:32",
    "Nome completo": "BEATRIZ FONSECA MORAES",
    "Razão Social do prestador de serviços": "BEATRIZ FONSECA MORAES",
    "Número do CNPJ": "53050717000104",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.05,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "NUBANK",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "71663340-3",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 53050717000104,
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": 53050717000104,
    "Número da nota fiscal (INFLUENCER)": 54,
    "Valor a pagar da nota fiscal (INFLUENCER)": 2300,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1x124XK9RVuQHUJfic6Gk-RUNHRzXk5Ir",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "Não validado",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Correto",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "53050717000104",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 19800,
    "ValorMensal_Planilha": 3300,
    "ValorMensal_Influ": 2300,
    "ValorMensal_Assessoria": 1000,
    "QtD_NFs": 6
  },
  {
    "Carimbo de data/hora": "01/07/2025 18:16:55",
    "Nome completo": "Carla da Gama Balta",
    "Razão Social do prestador de serviços": "32.724.771 CARLA DA GAMA BALTA",
    "Número do CNPJ": "32724771000118",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": "Não sou comissionada (o)",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "Inter",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "2355183-6",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 32724771000118,
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": 32724771000118,
    "Número da nota fiscal (INFLUENCER)": 202500000000079,
    "Valor a pagar da nota fiscal (INFLUENCER)": 6000,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1nvVxLumeN8ArrsRoPDsaVsp1n6DQRvSP",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "Não validado",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Correto",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "32724771000118",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 18000,
    "ValorMensal_Planilha": 6000,
    "ValorMensal_Influ": 6000,
    "ValorMensal_Assessoria": 0,
    "QtD_NFs": 3
  },
  {
    "Carimbo de data/hora": "02/07/2025 14:57:53",
    "Nome completo": "CAROLINA FERRAZ COSTA",
    "Razão Social do prestador de serviços": "CAROLINA FERRAZ COSTA",
    "Número do CNPJ": "39969278000107",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.05,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "Nubank",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "30609561-1",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "39.969.278/0001-07",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "39.969.278/0001-07",
    "Número da nota fiscal (INFLUENCER)": 101,
    "Valor a pagar da nota fiscal (INFLUENCER)": 5200,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1gbHW1LZW6qrNsOvMzVdCWwz57h2lM1vt",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "Não foi possível ler a NF",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Não foi possível ler a NF",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "39969278000107",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 39000,
    "ValorMensal_Planilha": 6500,
    "ValorMensal_Influ": 5200,
    "ValorMensal_Assessoria": 1300,
    "QtD_NFs": 6
  },
  {
    "Carimbo de data/hora": "02/07/2025 15:49:50",
    "Nome completo": "Cecília Pedersoli Sadala ",
    "Razão Social do prestador de serviços": "Cecília Pedersoli Sadala ",
    "Número do CNPJ": "48248738000107",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": "Não sou comissionada (o)",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "C6",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "21738126-0",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "48.248.738/0001-07",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "48.248.738/0001-07",
    "Número da nota fiscal (INFLUENCER)": 29,
    "Valor a pagar da nota fiscal (INFLUENCER)": 15000,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1ZPIp3Nk5sQonKEnbBac3VVe8gT6Vpo4U",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "Não validado",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Correto",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "48248738000107",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 90000,
    "ValorMensal_Planilha": 15000,
    "ValorMensal_Influ": 15000,
    "ValorMensal_Assessoria": 0,
    "QtD_NFs": 6
  },
  {
    "Carimbo de data/hora": "02/07/2025 15:49:50",
    "Nome completo": "Cecília Pedersoli Sadala ",
    "Razão Social do prestador de serviços": "Cecília Pedersoli Sadala ",
    "Número do CNPJ": "48248738000107",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": "Não sou comissionada (o)",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "C6",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "21738126-0",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "48.248.738/0001-07",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "48.248.738/0001-07",
    "Número da nota fiscal (INFLUENCER)": 29,
    "Valor a pagar da nota fiscal (INFLUENCER)": 15000,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1ZPIp3Nk5sQonKEnbBac3VVe8gT6Vpo4U",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "",
    "Status (influ)": "",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "48248738000107",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 90000,
    "ValorMensal_Planilha": 15000,
    "ValorMensal_Influ": 15000,
    "ValorMensal_Assessoria": 0,
    "QtD_NFs": 6
  },
  {
    "Carimbo de data/hora": "04/07/2025 13:46:39",
    "Nome completo": "maria eduarda povoleri grazzia",
    "Razão Social do prestador de serviços": "dg negocios e servicos ltda",
    "Número do CNPJ": "51543354000113",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.08,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "inter",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 305946200,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 51543354000113,
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "51.543.354/0001-13 ",
    "Número da nota fiscal (INFLUENCER)": 2717.76,
    "Valor a pagar da nota fiscal (INFLUENCER)": 2717.76,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1_qiuAKuTr9_MWE4zlYpA1l56odzFDca9",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "mariaeduardapgrazzia@hotmail.com",
    "Status (influ)": "Não validado",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Correto",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "51543354000113",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 8800,
    "ValorMensal_Planilha": 2200,
    "ValorMensal_Influ": 2200,
    "ValorMensal_Assessoria": 0,
    "QtD_NFs": 4
  },
  {
    "Carimbo de data/hora": "07/07/2025 10:34:01",
    "Nome completo": " ESTHER MELO PRODUCOES LTDA",
    "Razão Social do prestador de serviços": " ESTHER MELO PRODUCOES LTDA",
    "Número do CNPJ": "45205932000109",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.05,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "Nubank",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "10087047-1",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "45.205.932/0001-09",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "45.205.932/0001-09",
    "Número da nota fiscal (INFLUENCER)": 260,
    "Valor a pagar da nota fiscal (INFLUENCER)": 12500,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1ee29CbWUdNrhJiIxo3vgkG1Ua2WhC0jU",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "danila@4pillarsagencia.com",
    "Status (influ)": "Não validado",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Correto",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "45205932000109",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 108000,
    "ValorMensal_Planilha": 18000,
    "ValorMensal_Influ": 12500,
    "ValorMensal_Assessoria": 5500,
    "QtD_NFs": 6
  },
  {
    "Carimbo de data/hora": "07/07/2025 21:24:55",
    "Nome completo": "Fernanda Scherer Abbott",
    "Razão Social do prestador de serviços": "53.264.365 FERNANDA SCHERER ABBOTT",
    "Número do CNPJ": "53264365000190",
    "Se você é comissionada (o) qual o valor da sua comissão? (Caso não receba comissão marcar a opção que corresponde a isso)": 0.05,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: BANCO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 260,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: AGÊNCIA. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": 1,
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CONTA COM O DÍGITO. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "93737625-7",
    "Para que o pagamento possa ser validado, favor informar o dado solicitado: CHAVE PIX. \nLembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF. \nSua resposta\n": "CNPJ 53.264.365/0001-90",
    "Os dados bancários informados acima é referente a conta pessoa física ou pessoa jurídica?  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "Pessoa Jurídica",
    "Informar o dado de acordo com a opção marcada acima. Se a opção marcada foi CNPJ, informar o CNPJ.  Se a opção marcada foi CPF, informar o CPF.  Lembrando que a conta bancária deve ter ligação com o CNPJ que emitiu a NF": "53.264.365/0001-90",
    "Número da nota fiscal (INFLUENCER)": 55,
    "Valor a pagar da nota fiscal (INFLUENCER)": 4401.04,
    "Anexar abaixo o arquivo da Nota Fiscal (influencer). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "https://drive.google.com/open?id=1mz8LAVkPWpSf6XpeyiuXf0wq-uZ-WZfq",
    "Tem assessoria?": "Não",
    "Número da nota fiscal (ASSESSORIA)": "",
    "Valor a pagar da nota fiscal (ASSESSORIA)": "",
    "Anexar abaixo o arquivo da Nota Fiscal (assessoria). Ao anexar, é importante que o arquivo esteja renomeado da seguinte forma: \nExemplo: Larissa Silva de Lima - NF 01": "",
    "Endereço de e-mail": "fernanda.abbott1@gmail.com",
    "Status (influ)": "Não validado",
    "Status (assessoria)": "",
    "CNPJ_Tomador_Influ": "Correto",
    "CNPJ_Tomador_Assessoria": "",
    "CNPJ_Planilha": "53264365000190",
    "FormaPagamento": "NF",
    "ValorTotal_Planilha": 24000,
    "ValorMensal_Planilha": 4000,
    "ValorMensal_Influ": 4000,
    "ValorMensal_Assessoria": 0,
    "QtD_NFs": 6
  }
]